language: c
compiler:
  - gcc
  - clang
before_script:
  - wget ftp://xmlsoft.org/libxml2/libxml2-sources-2.6.29.tar.gz
  - tar -xvzf libxml2-sources-2.6.29.tar.gz
  - cd libxml2-2.6.29
  - ./configure --prefix=/usr/local/libxml2
  - make
  - sudo make install
script: make
